version: '3'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: karlbergsbro
    ports:
      - 5432:5432
